name: deploy

on: [ push, pull_request ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4
            -   name: Upload zip
                uses: actions/upload-artifact@v4
                with:
                    name: deploy
                    path: |
                        assets/
                        latex-files/
                        packages/
                        ressources-graphiques/
                        .latexmkrc
                        Makefile
                        rapportUTT.tex
                        rUTT.cls
            -   name: Compile LaTeX
                uses: xu-cheng/latex-action@v3
                with:
                    root_file: rapportUTT.tex
            -   name: Upload PDF
                uses: actions/upload-artifact@v4
                with:
                    name: rapportUTT
                    path: rapportUTT.pdf
