name: deploy

on: [ push, pull_request ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4
            -   name: Upload zip
                uses: actions/upload-artifact@v4
                with:
                    name: deploy
                    path: |
                        assets/
                        latex-files/
                        packages/
                        ressources-graphiques/
                        .latexmkrc
                        Makefile
                        rapportUTT.tex
                        rUTT.cls
